### ISSUE TITLE
information source

### ISSUE THREAD

**Issue by TarunTater** [uberspot/OpenTriviaQA#10]
Is there a way to only get the information source? 
For eg : From this question : 
#Q In 1972 a company named Waco released the first handheld electronic game. What was its name?
^ Tic Tac Toe
A Cross
B Tic Tac Toe
C Tetris
D Microvision

If I want this text : In 1972, a company named Waco released the first handheld electronic game called Tic Tac Toe

**Comment by uberspot** [comment]
I haven't written anything to extract this. You can look at the converter script https://github.com/uberspot/OpenTriviaQA/blob/master/converter.rb and just print out the questions only.
Or alternatively run the converter script, Get the json files that are outputted and then filter them with jq ( https://stedolan.github.io/jq/ ) to keep the questions only. :)
