### ISSUE TITLE
Legally dubious/dangerous

### ISSUE THREAD

**Issue by bmcarbaugh** [uberspot/OpenTriviaQA#11]
Just putting this out there in case anyone is considering using this in a commercial project:

This dataset is scraped from various websites like 123facts.com, which hold copyright over them. It's actually infringing on that site's copyrights pretty directly.

http://www.123facts.com/copyright.php

In that sense, the contents of this dataset aren't truly open source -- and because they're being shared under a CC license that absolves the creator of any liability, that means i
liability passes on to you.

If you were to take a question from this dataset, sourced from one of those sites, and use it verbatim in a commercial project, you would be opening yourself to a copyright infringement lawsuit.

For that reason, I think it's slightly irresponsible to call this an open source database. It's kind of legally rquivalent to scraping pictures off google inages, putting them in a zip folder, and slapping a creative commons license on it. Calling it CC content doesn't make it so.

**Comment by BombeyR** [comment]
Hello. Can someone please comment on this issue?

**Comment by dirkk0** [comment]
I'd like to know this, too, especially because 123facts (never heard of them) is down for more than a week.
![image](https://user-images.githubusercontent.com/625394/210372999-48de897d-5a1a-4f91-8b93-e3b2b81a780e.png)
