### ISSUE TITLE
some of the questions and answers are even wrong

### ISSUE THREAD

**Issue by arkilis** [uberspot/OpenTriviaQA#9]
#Q Three of these animals hibernate. Which one does not?
^ Sloth
A Mouse
B Sloth
C Frog
D Snake

Sloth & Mouse

**Comment by uberspot** [comment]
If you do a Pull Request I'll gladly merge it. I didn't validate all the questions manually. They were collected semi-automatically.

**Comment by boy1984** [comment]
Hi there,

Sorry that I am posting here I didn't find a way to contact you directly.

I was searching for a trivia QA for my mobile application and found this repo.
I would like to ask you if I can use QAs from this repo in my app?

Thank you!

Regards,
Aram.

**Comment by uberspot** [comment]
If you provide attribution according to the license yes. Check the license specifically for your use case. :)
